### ISSUE TITLE
Difficult read something in activity bar during debugging

### ISSUE THREAD

**Issue by epszaw** [adbayb/vscode-theme-honeymoon#1]
![image](https://user-images.githubusercontent.com/13414205/47445895-abc14f00-d7c2-11e8-9f20-b0dc3d7e570e.png)

P.S. Your theme really good 🙂

**Comment by adbayb** [comment]
First of all, thx for your feedback

What do you think of this :

![debugguer](https://user-images.githubusercontent.com/10498826/47617509-22629300-dac8-11e8-8fd3-2364216034e5.png)

**Comment by epszaw** [comment]
Yea, looks very pretty :)

**Comment by adbayb** [comment]
Just published: https://github.com/adbayb/vscode-theme-honeymoon/releases/tag/v0.1.0
